apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "comm-be.fullname" . }}
  annotations:
    {{- if .Values.Schedule }}
    Schedule: {{ .Values.Schedule }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "comm-be.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "comm-be.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.uiPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  strategy:
    blueGreen:
      activeService: {{ .Values.blueGreen.activeService }}
      autoPromotionEnabled: {{ .Values.blueGreen.autoPromotionEnabled }}
  
